export const mockProducts = [
    {
      id: 1,
      name: "Wireless Headphones",
      category: "Electronics",
      price: 199.99,
      rating: 4.5,
      image: "/images/headphones.jpg",
      description: "High-quality wireless headphones with noise cancellation.",
      features: ["Bluetooth 5.0", "20hr Battery", "Noise Cancellation"],
      reviews: [
        { user: "Alex", comment: "Superb sound!" },
        { user: "Jamie", comment: "Great battery life!" },
      ],
      specifications: {
        Color: "Black",
        Weight: "250g",
        Warranty: "1 year",
      },
    },
    {
        id: 2,
        name: "Smart Watch",
        category: "Electronics",
        price: 149.99,
        rating: 4.2,
        image: "/images/front-view-modern-dark-sunglasses-dark-blue.jpg", // ✅ correct
        description: "Smartwatch with fitness tracking and notifications.",
        features: ["Heart Rate Monitor", "Waterproof", "Sleep Tracking"],
        reviews: [{ user: "Sara", comment: "Very stylish and accurate!" }],
        specifications: {
          Color: "Silver",
          Battery: "7 days",
        },
    },
      
      
        {
          id: 3,
          name: "Gaming Mouse",
          category: "Electronics",
          price: 59.99,
          rating: 4.6,
          image: "/images/mouse.jpg",
          description: "High-precision mouse with RGB lighting.",
          features: ["16000 DPI", "Ergonomic", "Programmable Buttons"],
          reviews: [{ user: "Liam", comment: "Perfect for gaming!" }],
          specifications: {
            Color: "Black",
            Type: "Wired",
          },
        },
        {
          id: 4,
          name: "Yoga Mat",
          category: "Fitness",
          price: 29.99,
          rating: 4.1,
          image: "/images/yoga-mat.jpg",
          description: "Eco-friendly non-slip yoga mat for all levels.",
          features: ["Non-Slip", "6mm Thick", "Eco Material"],
          reviews: [{ user: "Maya", comment: "Really comfy and grippy!" }],
          specifications: {
            Material: "TPE",
            Length: "72 inches",
          },
        },
        {
          id: 5,
          name: "Stainless Steel Bottle",
          category: "Home",
          price: 19.99,
          rating: 4.7,
          image: "images/purple-computer-mouse.jpg",
          description: "Keeps drinks hot or cold for hours.",
          features: ["750ml", "Double Wall", "Leakproof"],
          reviews: [{ user: "Noah", comment: "Use it every day!" }],
          specifications: {
            Color: "Silver",
            Insulation: "12hrs hot/24hrs cold",
          },
        },
        {
          id: 6,
          name: "Running Shoes",
          category: "Fitness",
          price: 89.99,
          rating: 4.4,
          image: "/images/shoes.jpg",
          description: "Lightweight and breathable running shoes.",
          features: ["Breathable Mesh", "Shock Absorption", "Lightweight"],
          reviews: [{ user: "Emma", comment: "Super comfy for long runs!" }],
          specifications: {
            SizeRange: "6-12",
            Color: "Blue",
          },
        },
        {
          id: 7,
          name: "LED Desk Lamp",
          category: "Home",
          price: 34.99,
          rating: 4.3,
          image: "/images/desk-lamp.jpg",
          description: "Adjustable brightness LED lamp with USB charging port.",
          features: ["Touch Control", "3 Light Modes", "USB Port"],
          reviews: [{ user: "Olivia", comment: "Very handy and bright!" }],
          specifications: {
            Color: "White",
            Power: "10W",
          },
        },
        {
          id: 8,
          name: "Bluetooth Speaker",
          category: "Electronics",
          price: 79.99,
          rating: 4.8,
          image: "/images/speaker.jpg",
          description: "Portable speaker with rich bass and waterproof design.",
          features: ["IPX7 Waterproof", "12h Battery", "Deep Bass"],
          reviews: [{ user: "Jack", comment: "Awesome sound quality!" }],
          specifications: {
            Battery: "12 hours",
            Range: "10 meters",
          },
        },
        {
          id: 9,
          name: "Backpack",
          category: "Accessories",
          price: 49.99,
          rating: 4.5,
          image: "/images/backpack.jpg",
          description: "Spacious backpack with laptop compartment.",
          features: ["Water Resistant", "USB Port", "Laptop Sleeve"],
          reviews: [{ user: "Ava", comment: "Perfect for college!" }],
          specifications: {
            Capacity: "30L",
            Color: "Grey",
          },
        },
        {
          id: 10,
          name: "Sunglasses",
          category: "Accessories",
          price: 25.00,
          rating: 4.0,
          image: "/images/sunglasses.jpg",
          description: "UV protection stylish sunglasses.",
          features: ["UV400", "Scratch Resistant", "Unisex"],
          reviews: [{ user: "Ben", comment: "Looks great and protects eyes." }],
          specifications: {
            Frame: "Plastic",
            Lens: "Polarized",
          },
        },
        {
          id: 11,
          name: "Coffee Maker",
          category: "Home",
          price: 129.99,
          rating: 4.3,
          image: "/images/coffee-maker.jpg",
          description: "Brew perfect coffee every morning.",
          features: ["Programmable", "Auto Shutoff", "Glass Carafe"],
          reviews: [{ user: "Zoe", comment: "So easy and fast!" }],
          specifications: {
            Capacity: "1.2L",
            Power: "900W",
          },
        },
        {
          id: 12,
          name: "Digital Camera",
          category: "Electronics",
          price: 499.99,
          rating: 4.6,
          image: "/images/camera.jpg",
          description: "Capture moments with crystal clear clarity.",
          features: ["24MP", "WiFi", "4K Video"],
          reviews: [{ user: "Leo", comment: "Amazing quality photos!" }],
          specifications: {
            Lens: "18-55mm",
            Storage: "SD Card",
          },
        }
      ];
      
  